version: "3"
services:
  mongodb:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  mongodb-ui:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    ports:
      - 8081:8081

volumes:
  mongodb-data:
